WIP

diff --git a/blog/Earthfile b/blog/Earthfile
--- a/blog/Earthfile
+++ b/blog/Earthfile
@@ -63,24 +63,27 @@ update:
 ## Lint (Run in CI)
 lint:
   FROM +base-or-cache-image
+  RUN mkdir lint
   COPY ../+export/base .
   COPY . blog
-  RUN vale --output line --minAlertLevel error ./blog/_posts/*.md
+  RUN vale --output line --minAlertLevel error ./blog/_posts/*.md 2>&1 | tee -a ./lint/output.txt
   IF grep '[“”‘’]' ./blog/_posts/*.md
     RUN echo "Fail: Remove curly quotes and use straight quotes instead" && false
   END  
   IF grep -n 'imgur.com' ./blog/_posts/*.md
     RUN echo "Fail: external image link" && false
   END
-  RUN markdownlint "./blog/_posts/*.md"
+  RUN markdownlint "./blog/_posts/*.md" 2>&1 | tee -a ./lint/output.txt
 
-  # In order to check for warnings, we need to build all future posts and check the error out
-  # This is a unideal because it means we are building site twice but it prevents failing at 
-  # some future date when a post goes out.
-  RUN cd blog && bundle exec jekyll build --future 2> ../error.txt || true
-  IF [ -s error.txt ]
-    RUN cat error.txt && echo "Errors in Build" && false
-  END
+  # # In order to check for warnings, we need to build all future posts and check the error out
+  # # This is a unideal because it means we are building site twice but it prevents failing at 
+  # # some future date when a post goes out.
+  # RUN cd blog && bundle exec jekyll build --future 2> ../error.txt || true
+  # IF [ -s error.txt ]
+  #   RUN cat error.txt && echo "Errors in Build" && false
+  # END
+  ## SAVE results for use in CI output
+  SAVE ARTIFACT ./lint/output.txt AS LOCAL build/lint.txt
 
 ## Build (Run in CI)
 build:
