GHA better error messaging

diff --git a/.github/workflows/add-ctas.yaml b/.github/workflows/add-ctas.yaml
--- a/.github/workflows/add-ctas.yaml
+++ b/.github/workflows/add-ctas.yaml
@@ -3,12 +3,26 @@ name: Add CTAs and summaries to articles
 on:
   pull_request:
     types: [opened, reopened]
+  workflow_dispatch:
 
 jobs:
   create-pr:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Check Required Secrets
+      run: |
+        if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
+          echo "Error: OPENAI_API_KEY is not set."
+          exit 1
+        fi
+        if [ -z "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
+          echo "Error: ANTHROPIC_API_KEY is not set."
+          exit 1
+        fi
+      env:
+        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 
+        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }} 
     - name: Checkout PR
       uses: actions/checkout@v2
       with:
